site_name: RedBlackDbTree Documentation
site_url: https://theeman05.github.io/RedBlackDbTree/
repo_name: theeman05/RedBlackDbTree
repo_url: https://github.com/theeman05/RedBlackDbTree

theme:
  name: material
  highlightjs: true
  hljs_style: github-dark
  palette:
    scheme: slate
    primary: deep orange

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
- Home: index.md
- Guide:
  - Installation: guide/installation.md
  - Implimentation: guide/implimentation.md
  - Array Retrieval: guide/array-retrieval.md
  - Custom Comparator: guide/custom-comparator.md
  - Mutable Objects: guide/mutable-objects.md
- API Reference: api-reference.md